"""itog

Revision ID: 8ddf71f6c4af
Revises: 9d927b2a2a03
Create Date: 2024-06-28 00:18:15.289893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddf71f6c4af'
down_revision = '9d927b2a2a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_book_collection_collection.id_collections', table_name='book_collection')
    op.drop_constraint('uq_collections_name', 'collections', type_='unique')
    op.create_unique_constraint(op.f('uq_collections_name'), 'collections', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_collections_name'), 'collections', type_='unique')
    op.create_unique_constraint('uq_collections_name', 'collections', ['name', 'user_id'])
    op.create_index('fk_book_collection_collection.id_collections', 'book_collection', ['collection.id'], unique=False)
    # ### end Alembic commands ###
