"""create_table_review_statuses

Revision ID: 9d927b2a2a03
Revises: 7baa03583ee2
Create Date: 2024-06-22 16:24:05.327632

"""
from alembic import op
import sqlalchemy as sa

from app.constants import REVIEW_STATUSES

# revision identifiers, used by Alembic.
revision = '9d927b2a2a03'
down_revision = '7baa03583ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_statuses'))
    )
    op.add_column('reviews', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_status_id_review_statuses'), 'reviews', 'review_statuses', ['status_id'], ['id'])

    data_upgrades()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_status_id_review_statuses'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'status_id')
    op.drop_table('review_statuses')
    # ### end Alembic commands ###


def data_upgrades():
    table = sa.sql.table('review_statuses', sa.sql.column('name', sa.String))
    op.bulk_insert(table, list(REVIEW_STATUSES.values()))

